
dofile(minetest.get_modpath("mystreets").."/asphalt.lua")
dofile(minetest.get_modpath("mystreets").."/asphalt_crafts.lua")
dofile(minetest.get_modpath("mystreets").."/concrete.lua")
dofile(minetest.get_modpath("mystreets").."/lights.lua")
dofile(minetest.get_modpath("mystreets").."/mapgen.lua")
dofile(minetest.get_modpath("mystreets").."/oil.lua")
dofile(minetest.get_modpath("mystreets").."/paint.lua")
dofile(minetest.get_modpath("mystreets").."/posts.lua")
dofile(minetest.get_modpath("mystreets").."/ramps.lua")	
dofile(minetest.get_modpath("mystreets").."/steel.lua")
dofile(minetest.get_modpath("mystreets").."/streetsigns.lua")
dofile(minetest.get_modpath("mystreets").."/traffic_light.lua")	
dofile(minetest.get_modpath("mystreets").."/manholes.lua")	
dofile(minetest.get_modpath("mystreets").."/sewerwater.lua")
dofile(minetest.get_modpath("mystreets").."/ores.lua")
dofile(minetest.get_modpath("mystreets").."/powerpoles.lua")
dofile(minetest.get_modpath("mystreets").."/billboard.lua")	
dofile(minetest.get_modpath("mystreets").."/railroad_crossing.lua")	
dofile(minetest.get_modpath("mystreets").."/traffic_cone.lua")	
dofile(minetest.get_modpath("mystreets").."/plastic.lua")
print("mystreets mod loaded succesfully!")
